---
# tasks file for lamp_docker
- name: Create docker directory
  file:
    path: docker
    state: directory

- name: Copy from docker directory files to remote machine
  copy:
    src: docker/
    dest: docker/

- name: Build Web server Docker image from Dockerfile
  docker_image:
    name: "{{ web_docker_img_name }}"
    build:
      path: "{{ web_dockerfile_path }}"
      pull: no
    state: present
    source: build
  register: web_docker_img

- name: Build DB server Docker image from Dockerfile
  docker_image:
    name: "{{ db_docker_img_name }}"
    build:
      path: "{{ db_dockerfile_path }}"
      pull: no
    state: present
    source: build
  register: db_docker_img

- name: Clear IPTables filter
  shell: iptables -F; iptables -X
  when: web_docker_img.changed or db_docker_img.changed

- name: Restart Docker
  service:
    name: docker
    state: restarted
  when: web_docker_img.changed or db_docker_img.changed
